#!/bin/sh
alias ka="killall" \
  :q="exit" \
  gp="gnuplot" \
  config="git --git-dir=$HOME/.dotfiles --work-tree=$HOME" \
  runcl="cd ~/Documents/cl/code; [[ -f cl ]] || make; ./cl net3_4_2 trainfile testfile" \
  vruncl="./cl net3_4_2 vec_trainfile vec_trainfile" \
  101runcl="./cl net1_0_1 vec_trainfile vec_trainfile" \
  201runcl="./cl net2_0_1 vec_trainfile vec_trainfile" \
  111runcl="./cl net1_1_1 vec_trainfile vec_trainfile" \
  info="pinfo" \
  guitao="tao -init ~/bmad_dist/tao/gui/cesrbeam/cesr_beam.init -noplot -external_plotting" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	x2go="x2goclient" \
  bmad_update="~/bmad_dist/update.sh" \
  bmad_backup="/home/john/bmad_dist/backup.sh" \
  lab="ssh -XY jmm699@lnx201.lepp.cornell.edu" \
  tpcmd="vim ~/bmad_dist/tao/code/tao_python_cmd.f90" \
  py="python" \
  gui="cd ~/bmad_dist/tao/gui && python main.py" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}
