#!/bin/sh
alias ka="killall" \
  cp="cp -iv" \
  mv="mv -iv" \
  :q="exit" \
  gp="gnuplot" \
  mutt="neomutt" \
  gga="git add" \
  ggs="git status" \
  ggc="git commit" \
  ggp="git push 2>/dev/null || ssh-add && git push" \
  ggpl="git pull 2>/dev/null || ssh-add && git pull" \
  config="git --git-dir=$HOME/.dotfiles --work-tree=$HOME" \
  runcl="cd ~/Documents/cl/code; [[ -f cl ]] || make; ./cl net3_4_2 trainfile testfile" \
  vruncl="./cl net3_4_2 vec_trainfile vec_trainfile" \
  101runcl="./cl net1_0_1 vec_trainfile vec_trainfile" \
  111runcl="./cl net1_1_1 vec_trainfile vec_trainfile" \
  201runcl="./cl net2_0_1 vec_trainfile vec_trainfile" \
  info="pinfo" \
  guitao="tao -init ~/bmad_dist/tao/gui/cesrbeam/cesr_beam.init -noplot -external_plotting" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	x2go="x2goclient" \
  bmad_update="~/bmad_dist/update.sh" \
  bmad_backup="/home/john/bmad_dist/backup.sh" \
  tpcmd="vim ~/bmad_dist/tao/code/tao_python_cmd.f90" \
  py="python" \
  gui="cd ~/bmad_dist/tao/gui && python main.py" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="exa --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
  octave="octave --gui" \
  abook="abook --config $XDG_CONFIG_HOME/abook/abookrc --datafile $XDG_CONFIG_HOME/abook/addressbook" \
  bash="bash --init-file $XDG_CONFIG_HOME/bash/bashrc" \
  mbsync="mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc" \
  svn="svn --config-dir $XDG_CONFIG_HOME/subversion" \
  nvr="sudo nvidia-settings --config=$XDG_CONFIG_HOME/nvidia/settings" \
  cos="converter_simulation" \
  cof="converter_fitter" \
  gstf="git add -A; git status; git commit -m stuff; git push" \
  carb="TERM=xterm ssh -XY -o StrictHostKeyChecking=off jmastrob@carbonate.uits.iu.edu" \
  bigred="TERM=xterm ssh -XY -o StrictHostKeyChecking=off jmastrob@bigred3.uits.iu.edu" \
  cohbr="TERM=xterm ssh -XY coherent@bigred3.uits.iu.edu" \
  hcdata="ssh -XY jmastrob@hcdata.phy.ornl.gov" \
  sns="ssh -XY jmastrob@coherent.sns.gov" \
  orphans="pacman -Qtdq | sudo pacman -Rns -" \



command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}
