#!/bin/sh

#setbg &		# Set the background
#sxhkd &	# Bind keys
refreshkeys & # Set up keyboard
unclutter &		# Remove mouse when idle
dunst &			# dunst for notifications
mpd &
mpdupdate &
# GNOME keyring:
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
