#!/bin/sh

#setbg &		# Set the background
#sxhkd &	# Bind keys
refreshkeys & # Set up keyboard
[ -f "/home/john/.config/Xresources" ] && xrdb /home/john/.config/Xresources
[ -f "$HOME/.config/screens.sh" ] && source "$HOME/.config/screens.sh"
#unclutter &		# Remove mouse when idle
#dunst &			# dunst for notifications
mpd &
mpdupdate &
# GNOME keyring:
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
