#! /bin/sh

sxhkd &
compton &
startpolybar &

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDM1-1 -d 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Surf state=tiling
bspc rule -a Tao desktop='^5' state=floating
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
