#! /bin/sh

#xrdb ~/.config/bspwm/.low_alpha
sxhkd &
compton &
startpolybar &
setbg &
# Shuffle wallpapers
while true; do
  setbg "/home/john/Pictures/backgrounds/$(ls /home/john/Pictures/backgrounds/ | shuf | head -n 1)"
  sleep 10m
done &
#dropbox &

if [ $HOSTNAME == "john-pc" ]; then
  bspc monitor DP-0 -d 1 2 3 4 5
  bspc monitor DP-2 -d 6 7 8 9 10
else
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi
#if [$HOSTNAME == "john-pc"]; then
#bspc monitor DP-0 -d 1 2 3 4 5
#bspc monitor DP-2 -d 6 7 8 9 10
##else
#bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
#fi

bspc config border_width         0
bspc config window_gap           6
bspc config top_padding          32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a '*:surf' state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Tao desktop='^5' state=floating
bspc rule -a "*:PGPLOT Window 1" state=floating
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
